- name: Mettre à jour le cache APT
  apt:
    update_cache: yes

- name: Installer MariaDB depuis les dépôts Debian
  apt:
    name: mariadb-server
    state: present

- name: Démarrer et activer MariaDB
  service:
    name: mariadb
    state: started
    enabled: yes

- name: Sécuriser MariaDB (désactiver root remote login)
  mysql_user:
    name: root
    host: "{{ item }}"
    password: ""
    state: absent
  with_items:
    - "127.0.0.1"
    - "::1"
    - "localhost"

- name: Créer la base de données "{{ mariadb_database }}"
  mysql_db:
    name: "{{ mariadb_database }}"
    state: present

- name: Créer l'utilisateur "{{ mariadb_user }}"
  mysql_user:
    name: "{{ mariadb_user }}"
    password: "{{ mariadb_password }}"
    priv: "{{ mariadb_database }}.*:ALL"
    host: "%"
    state: present
