---
- name: Add MariaDB repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64,arm64,ppc64el,s390x] http://mirror.mariadb.org/repo/{{ mariadb_version }}/debian bullseye main"
    state: present
    update_cache: yes

- name: Install MariaDB and Galera
  ansible.builtin.apt:
    name:
      - mariadb-server
      - galera-4
    state: present
    update_cache: yes

- name: Configure MariaDB for Galera
  ansible.builtin.template:
    src: my.cnf.j2
    dest: /etc/mysql/my.cnf
    owner: root
    group: root
    mode: 0644
  notify: Restart MariaDB

- name: Ensure MariaDB service is started and enabled
  ansible.builtin.service:
    name: mariadb
    state: started
    enabled: yes
